#!/usr/bin/env bash
# Script that installs and configures Nginx on Ubuntu

apt-get update -y

apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

service nginx start

update-rc.d nginx enable